name: Ping GitHub Server At Minute 20 Every Hour

on:
  schedule:
    - cron: '*/10 * * * *'

permissions: {}

jobs:
  run-ping-to-github-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping GitHub server
        run: ping -c 4 github.com
